language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.6
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install coveralls
  - pip install -q -e .
before_script:
  - "flake8 mojo"
script:
  - coverage run mojo/navigation/tests/manage.py test mojo.navigation
after_success: coveralls
