language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django==1.7"
    - python: "3.5"
      env: DJANGO="Django<=1.7"
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install coveralls
  - pip install -q -e .
before_script:
  - "flake8 mojo"
script:
  - coverage run mojo/navigation/tests/manage.py test mojo.navigation
after_success: coveralls
