language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.7
  - DJANGO=1.8
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO=1.7
install:
  - pip install -q Django==$DJANGO
  - pip install flake8
  - pip install coveralls
  - pip install -q -e .
before_script:
  - "flake8 mojo"
script:
  - coverage run --source mojo.navigation mojo/navigation/tests/manage.py test mojo.navigation.tests
after_success: coveralls
